global:
  namespace: kathra-dev
  tld: dev-irtsysx.fr
  docker:
    registry: 
      url: registry.hub.docker.com/
      root_repository: kathra
      secret_b64: <base64_k8s_dockerconfig_secret>
  keycloak:
    kathra_services_client:
      id: <kathra_services_client_id>
      secret: <kathra_services_client_secret>

image: pipelinemanager-jenkins
version: 1.0.0
tls: true
jenkins:
  url: https://jenkins.dev-irtsysx.fr
  username: <jenkins_service_acc_name>
  api_token: <jenkins_service_acc_token>
resources:
  limits:
    cpu: 300m
    memory: 768Mi
  requests:
    cpu: 50m
    memory: 128Mi

#ingress:
#  annotations:
#    kubernetes.io/ingress.class: traefik
#    cert-manager.io/cluster-issuer: letsencrypt-prod
#  tls:
#  - hosts:
#    - pipelinemanager.irtsystemx.org
#    secretName: pipelinemanager-cert