{{- if .Values.postInstallConfig.enabled -}}
{{ if eq .Values.auth.mode "oidc_auth" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-oidc-cm
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  HARBOR_CONFIGURATIONS_ENDPOINT: {{ .Values.externalURL }}/api/configurations
  HARBOR_API_ENDPOINT: {{ .Values.externalURL }}/api/p.groupGid }}
  OIDC_ENDPOINT: {{ .Values.auth.oidc.endpoint }}
  OIDC_SCOPE: {{ .Values.auth.oidc.scope }}
  OIDC_CLIENT_ID: {{ .Values.auth.oidc.clientId }}
  OIDC_CLIENT_SECRET: {{ .Values.auth.oidc.clientSecret }}
  {{ (.Files.Glob "config/oidc-config.sh").AsConfig | nindent 2 }}
{{- end -}}
{{- end -}}