apiVersion: v1
kind: Secret
metadata:
  name: jenkins-maven-settings-xml
  labels:
    app: {{ template "jenkins.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  settings.xml: {{ include "maven-settings.xml" . | b64enc }}
