apiVersion: v1
kind: Secret
metadata:
  name: jenkins-docker-config-json
  labels:
    app: {{ template "jenkins.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  config.json: {{ include "docker-config.json" . | b64enc }}
