apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: icons
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
{{ include "kathra.labels" . | indent 4 }}
    ingress: "{{ if .Values.tls }}tls{{ else }}plain{{ end }}"
spec:
  rules:
  - host: "icons.{{ .Values.global.domain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: catalog-icons
          servicePort: 80