stages:
  - installK8S
  - installKathra
  - initKathraCli
  - createComponent
  - initImportKathraComponent

variables:
  DOMAIN_NAME: kathra.boubechtoula.ovh
  TLS_CERT: /etc/letsencrypt/live/kathra.boubechtoula.ovh/fullchain.pem
  TLS_KEY: /etc/letsencrypt/live/kathra.boubechtoula.ovh/privkey.pem
  NETWORK_DEVICE: enp4s0
  USER_LOGIN: userTest
  USER_PASSWORD: passwordTest

installK8S:
  stage: installK8S
  tags: 
    - workstation
  script: 
    - ./install-minikube.sh --domain=$DOMAIN_NAME --tlsCert=$TLS_CERT --tlsKey=$TLS_KEY --network-device=$NETWORK_DEVICE --verbose

installKathra:
  stage: installKathra
  tags: 
    - workstation
  script: 
    - ./install.sh --domain=$DOMAIN_NAME --user-login=$USER_LOGIN --user-password=$USER_PASSWORD --verbose

initKathraCli:
  stage: initKathraCli
  tags: 
    - workstation
  script: 
    - git clone --branch=feature_login https://gitlab.com/kathra/kathra/kathra-cli.git
    - ./kathra-cli/kathra-cli.sh login --username=$USER_LOGIN --password=$USER_PASSWORD
    - ./kathra-cli/kathra-cli.sh get components

createComponent:
  stage: createComponent
  tags: 
    - workstation
  script: 
    - ./kathra-cli/kathra-cli.sh create components "./kathra-cli/swagger.example.yaml" "my-first-component" "my-team" "Component's description"

initImportKathraComponent:
  stage: initImportKathraComponent
  tags: 
    - workstation
  script: 
    - ./kathra-cli/init-kathra-components.sh kathra-components.json kathra-pipelinemanager