stages:
  - installMinikube
  - installKathra
  - initKathraCli
  - createComponent
  - createImplPython
  - createImplJava
  - deleteComponent
  - initImportKathraComponent

variables:
  USER_LOGIN: userTest
  USER_PASSWORD: passwordTest
  USER_TEAM: team-test-e2e
  DISK_SIZE: 30000mb
  KATHRA_VERSION: latest


installMinikube:
  stage: installMinikube
  only:
    - master
  tags: 
    - sudoers
  script: 
    - minikube delete || echo "No cluster to delete"
    - ./install-minikube.sh --domain=$DOMAIN_NAME --tlsCert=$TLS_CERT --tlsKey=$TLS_KEY --network-device=$NETWORK_DEVICE --disk-size=$DISK_SIZE --verbose

installKathra:
  stage: installKathra
  only:
    - master
  tags: 
    - sudoers
  script: 
    - ./install.sh --kathra-image-tag=KATHRA_VERSION --domain=$DOMAIN_NAME --user-login=$USER_LOGIN --user-password=$USER_PASSWORD --user-team=$USER_TEAM --verbose

initKathraCli:
  stage: initKathraCli
  only:
    - master
  tags: 
    - sudoers
  script: 
    - git clone https://gitlab.com/kathra/kathra/kathra-cli.git
    - ./kathra-cli/kathra-cli.sh login --username=$USER_LOGIN --password=$USER_PASSWORD
    - ./kathra-cli/kathra-cli.sh get groups | jq -r '.name' | grep "^$USER_TEAM\$"

createComponent:
  stage: createComponent
  only:
    - master
  tags: 
    - sudoers
  script: 
    - git clone https://gitlab.com/kathra/kathra/kathra-cli.git
    - ./kathra-cli/kathra-cli.sh create components "./kathra-cli/swagger.example.yaml" "my-first-component" "$USER_TEAM" "Component's description"
    - ./kathra-cli/kathra-cli.sh get components 

createImplJava:
  stage: createImplJava
  only:
    - master
  tags: 
    - sudoers
  script: 
    - git clone https://gitlab.com/kathra/kathra/kathra-cli.git
    - ./kathra-cli/kathra-cli.sh create implementations "my-java-implementation" "my-first-component" "1.0.0" "JAVA" "Java implementation description"
    - 'curl -v -H "Host: my-first-component.$USER_TEAM-dev.kathra.boubechtoula.ovh" http://$(dig +short dashboard.${DOMAIN_NAME})/api/v1/swagger.json > /dev/null'

createImplPython:
  stage: createImplPython
  only:
    - master
  tags: 
    - sudoers
  script: 
    - git clone https://gitlab.com/kathra/kathra/kathra-cli.git
    - ./kathra-cli/kathra-cli.sh create implementations "my-python-implementation" "my-first-component" "1.0.0" "PYTHON" "Python implementation description"
    - 'curl --fail -v -H "Host: my-first-component.$USER_TEAM-dev.kathra.boubechtoula.ovh" http://$(dig +short dashboard.${DOMAIN_NAME})/api/v1/swagger.json > /dev/null'

deleteComponent:
  stage: deleteComponent
  only:
    - master
  tags: 
    - sudoers
  script: 
    - git clone https://gitlab.com/kathra/kathra/kathra-cli.git
    - ./kathra-cli/kathra-cli.sh delete components "$(./kathra-cli/kathra-cli.sh get components "my-first-component" | jq -r '.id')" --purge

initImportKathraComponent:
  stage: initImportKathraComponent
  only:
    - master
  tags: 
    - sudoers
  script: 
    - git clone https://gitlab.com/kathra/kathra/kathra-cli.git
    - sed "s/\"my-team\"/\"$USER_TEAM\"/" < ./kathra-cli/kathra-components.json > ./kathra-components.json
    - ./kathra-cli/init-kathra-components.sh ./kathra-components.json