apiVersion: v1
kind: Service
metadata:
  name: codegen-helm
  labels:
{{ include "kathra.labels" . | indent 4 }}
    app: codegen
    project: kathra
    impl: helm
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: codegen
    project: kathra
    impl: helm
  type: ClusterIP