apiVersion:  apps/v1
kind: Deployment
metadata:
  name: kathra-codegen-helm
  labels:
{{ include "kathra.labels" . | indent 4 }}
    app: codegen
    project: kathra
    impl: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codegen
      project: kathra
      impl: helm
  template:
    metadata:
      labels:
        app: codegen
        project: kathra
        impl: helm
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: "{{ .Values.global.docker.registry.url }}/{{ .Values.global.docker.registry.root_repository }}/{{ .Values.image }}:{{ .Values.version }}"
        imagePullPolicy: Always
        name: codegen-helm
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: JAVA_OPTS
          value: "-XX:+UnlockExperimentalVMOptions  -XX:MaxRAMFraction=1 -Xms128M -Xmx512M"
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}