global:
  namespace: kathra-dev
  tld: dev-irtsysx.fr
  docker:
    registry: 
      url: registry.hub.docker.com
      root_repository: kathra
      secret_b64: <base64_k8s_dockerconfig_secret>
  keycloak:
    kathra_services_client:
      id: <kathra_services_client_id>
      secret: <kathra_services_client_secret>

image: kathra-platformmanager
version: 1.3.0-f52a917-12
tls: true
websocket:
  port: "8080"
catalog_manager:
  url: http://catalogmanager/api/v1
deployment:
  ingress_controller: traefik
  tld: dev-irtsysx.fr
resources:
  limits:
    cpu: 300m
    memory: 768Mi
  requests:
    cpu: 50m
    memory: 128Mi
ingress:
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/issuer: letsencrypt-prod
  tls:
  - hosts:
    - platformmanager.${BASE_DOMAIN}
    secretName: platformmanager-cert
