global:
  docker:
    registry: 
      url: registry.hub.docker.com
      root_repository: kathra
      secret_b64: <base64_k8s_dockerconfig_secret>

keycloak:
    clientId: <admin-keycloak>
    clientSecret: <pwd>

image: usermanager-keycloak
version: 1.0.0-RC-SNAPSHOT-6a96c96-87
resources:
  limits:
    cpu: 300m
    memory: 768Mi
  requests:
    cpu: 50m
    memory: 128Mi