global:
  docker:
    registry: 
      url: registry.hub.docker.com/
      root_repository: kathra
      secret_b64: <base64_k8s_dockerconfig_secret>

keycloak:
  adminRealm: <adminRealm>
  adminClientId: <admin-keycloak>
  adminUsername: <adminUsername>
  adminPassword: <passwordPassword>

image: usermanager-keycloak
version: 1.0.0
resources:
  limits:
    cpu: 300m
    memory: 768Mi
  requests:
    cpu: 50m
    memory: 128Mi