apiVersion: v1
kind: Secret
metadata:
  name: resource-manager-secret
  labels:
{{ include "kathra.labels" . | indent 4 }}
    project: kathra
    app: resource-manager
type: Opaque
data:
  ARANGODB_USER: {{ .Values.arango.user | b64enc }}
  ARANGODB_PASSWORD: {{ .Values.arango.password | b64enc }}
