apiVersion: v1
kind: Secret
metadata:
  name: pipeline-manager-secret
  labels:
{{ include "kathra.labels" . | indent 4 }}
    project: kathra
    app: pipeline-manager
type: Opaque
data:
  JENKINS_ACCOUNT_API_TOKEN: {{ .Values.jenkins.api_token | b64enc }}
  JENKINS_ACCOUNT_NAME: {{ .Values.jenkins.username | b64enc }}
