apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pipelinemanager
  annotations:
{{- with .Values.ingress.annotations }}
  labels:
{{ include "kathra.labels" . | indent 4 }}
    ingress: "{{ if .Values.tls }}tls{{ else }}plain{{ end }}"
spec:
  rules:
  - host: "pipelinemanager.{{ .Values.global.domain }}"
    http:
      paths:
      - backend:
          serviceName: pipelinemanager
          servicePort: 80
{{- with .Values.ingress.tls }}
  tls:
{{ toYaml . | indent 4 }}
{{- end }}