apiVersion: v1
kind: Secret
metadata:
  name: sync-secret
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": "hook-succeeded"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
{{ include "kathra.labels" . | indent 4 }}
    project: kathra
    app: kathra-sync
type: Opaque
data:
  USERNAME: {{ .Values.keycloak.login | b64enc }}
  PASSWORD: {{ .Values.keycloak.password | b64enc }}