global:
  namespace: kathra-dev
  tld: dev-irtsysx.fr
  docker:
    registry: 
      url: registry.hub.docker.com/
      root_repository: kathra
      secret_b64: <base64_k8s_dockerconfig_secret>
  keycloak:
    kathra_services_client:
      id: <kathra_services_client_id>
      secret: <kathra_services_client_secret>

image: codegen-helm
version: 1.0.0
tls: true
resources:
  limits:
    cpu: 300m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
