global:
  namespace: kathra-dev
  tld: dev-irtsysx.fr
  docker:
    registry: 
      url: registry.hub.docker.com/
      root_repository: kathra
      secret_b64: <base64_k8s_dockerconfig_secret>
  keycloak:
    kathra_services_client:
      id: <kathra_services_client_id>
      secret: <kathra_services_client_secret>

image: resourcemanager-arangodb
version: 1.0.0
tls: true
arango:
  host: resource-db
  port: "8529"
  database: KATHRA
  user: <arango_username>
  password: <arango_password>
resources:
  limits:
    cpu: 1
    memory: 2Gi
    cpu: 50m
    memory: 128Mi
    
#ingress:
#  annotations:
#    kubernetes.io/ingress.class: traefik
#    cert-manager.io/issuer: letsencrypt-prod
#  tls:
#  - hosts:
#    - resourcemanager.irtsystemx.org
#    secretName: resourcemanager-cert