apiVersion: v1
kind: Secret
metadata:
  name: appmanager-secret
  labels:
{{ include "kathra.labels" . | indent 4 }}
    project: kathra
    app: appmanager
type: Opaque
data:
  USERNAME: {{ .Values.technicalUser.username | b64enc }}
  PASSWORD: {{ .Values.technicalUser.password | b64enc }}