kind: Service
apiVersion: v1
metadata:
  name: "appmanager"
  labels:
{{ include "kathra.labels" . | indent 4 }}
    project: kathra
    app: appmanager
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    project: kathra
    app: appmanager
  type: ClusterIP