---
apiVersion: v1
kind: Secret
metadata:
  name: deploymanager-secret
  labels:
{{ include "factory.labels" . | indent 4 }}
    project: kathra
    app: deploymanager
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.username | b64enc }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.password | b64enc }}
