---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-webui
  labels:
{{ include "factory.labels" . | indent 4 }}
    project: kathra
    app: rabbitmq-deploymanager
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 15672
  selector:
    project: kathra
    app: rabbitmq-deploymanager

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
{{ include "factory.labels" . | indent 4 }}
    project: kathra
    app: rabbitmq-deploymanager
spec:
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
{{ if and (.Values.rabbitmq.serviceType) (eq .Values.rabbitmq.serviceType "NodePort") }}
      nodePort: {{ .Values.rabbitmq.nodePort }}
  type: {{ .Values.rabbitmq.serviceType }}
{{ else }}
  type: ClusterIP
{{ end }}
  selector:
    project: kathra
    app: rabbitmq-deploymanager