image: registry.hub.docker.com/kathra/deploymanager-k8s
tag: 1.0.0-RC-SNAPSHOT
mode: master
targetCluster: interne
domain: irtsystemx.org
protocol: https

docker:
  KATHRA_DOCKER_URL: registry.hub.docker.com
  KATHRA_DOCKER_AUTH: undefined:undefined
  TARGET_DOCKER_URL: harbor.<undefined>
  TARGET_DOCKER_AUTH: <undefined>:<undefined>

resources: {}
    
rabbitmq:
  image: rabbitmq
  version: 3.7.4-management-alpine
  url: rabbitmq
  serviceType: ClusterIP
  username: guest
  password: guest
  nodePort: "31965"
  resources: {}
