global:
  namespace: kathra-dev
  tld: dev-irtsysx.fr
  docker:
    registry: 
      url: registry.hub.docker.com
      root_repository: kathra
      secret_b64: <base64_k8s_dockerconfig_secret>

image: catalogmanager-helm
version: featureCatalogManager
tls: true
helm:
  repoName: kathra
  url: <harbor_url>
  username: <harbor_svc_username>
  password: <harbor_svc_password>
services_url:
  resource_manager: <undefined>
resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 256Mi