---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogmanager-config
  labels:
{{ include "kathra.labels" . | indent 4 }}
    project: kathra
    app: catalogmanager
data:
  KATHRA_REPO_NAME: {{ .Values.helm.repoName }}
  KATHRA_REPO_URL: {{ .Values.helm.url }}
  HELM_UPDATE_INTERVAL: "* * * * *"