apiVersion: v1
kind: Secret
metadata:
  name: catalogmanager-secret
  labels:
{{ include "kathra.labels" . | indent 4 }}
    project: kathra
    app: catalogmanager
type: Opaque
data:
  repositories.yaml: {{ include "repositories_helm.yaml" . | b64enc }}
  PASSWORD: {{ .Values.keycloak.login | b64enc }}
  USERNAME: {{ .Values.keycloak.password | b64enc }}