apiVersion: v1
kind: Secret
metadata:
  name: catalogmanager-secret
  labels:
{{ include "kathra.labels" . | indent 4 }}
    project: kathra
    app: catalogmanager
type: Opaque
data:
  KATHRA_REPO_CREDENTIAL_ID: {{ .Values.harbor.username | b64enc }}
  KATHRA_REPO_SECRET: {{ .Values.harbor.password | b64enc }}