global:
    docker:
        registry:
            secret: ewoJImF1dGhzIjogewoJCSJoYXJib3IuaXJ0c3lzeC5mciI6IHsKCQkJImF1dGgiOiAiYW1WdWEybHVjeTVvWVhKaWIzSTZSWGRrWTBSRlNVdEdTamg1YVZORFMzZ3dNRm89IgoJCX0sCiAgICAgICAgICAgICAgICAiaGFyYm9yLmRldi1pcnRzeXN4LmZyIjogewogICAgICAgICAgICAgICAgICAgICAgICAiYXV0aCI6ICJhbVZ1YTJsdWN5NW9ZWEppYjNJNlJYZGtZMFJGU1V0R1NqaDVhVk5EUzNnd01Gbz0iCiAgICAgICAgICAgICAgICB9Cgl9Cn0=
    keycloak:
        kathra_services_client:
            id: kathra-resource-manager
            secret: 184863e6-0b78-4df6-ae99-38b4003f6db5
kathra-binaryrepositorymanager-harbor:
    harbor:
        username: admin
        password: <undefined>
