## OVERIDE CHILDREN CHARTS' VALUES FROM HERE 
## OR MODIFY THEM IN THEIR RESPECTIVE CHART
global:
  tld: irtsystemx.org
  domain: <base-domain-name>
  docker:
    registry: 
      url: registry.hub.docker.com
      root_repository: kathra
      secret: eyJhdXRocyI6eyJoYXJib3IuaXJ0c3lzeC5mciI6eyJ1c2VybmFtZSI6ImplbmtpbnMuaGFyYm9yIiwicGFzc3dvcmQiOiJFd2RjREVJS0ZKOHlpU0NLeDAwWiIsImVtYWlsIjoiamVua2lucy5oYXJib3JAbm8tcmVwbHktaXJ0c3lzeC5mciIsImF1dGgiOiJhbVZ1YTJsdWN5NW9ZWEppYjNJNlJYZGtZMFJGU1V0R1NqaDVhVk5EUzNnd01Gbz0ifX19
  keycloak:
    auth_url: https://<keycloak-host>/auth
    realm: kathra
    kathra_services_client:
      id: resource-manager
      secret: 0d4df3ff-a332-446e-a877-d81947f7dc08

kathra-appmanager:
  image: appmanager
  version: 1.0.0
  tls: true
  delete_zip_file: "true"
  image_registry_host: <harbor-host>
  services_url:
    codegen_helm: codegen-helm/api/v1
    codegen_swagger: codegen-swagger/api/v1
    binaryrepository_harbor: binaryrepository_harbor/api/v1
    source_manager: sourcemanager/api/v1
    pipeline_manager: pipelinemanager/api/v1
    resource_manager: resourcemanager/api/v1
    catalogmanager: catalogmanager/api/v1
    pipeline_webhook: https://appmanager.<base-domain-name>/api/v1/webhook
  resources:
    limits:
      cpu: "300m"
      memory: "768Mi"
    requests:
      cpu: "50m"
      memory: "256Mi"

kathra-binaryrepositorymanager-harbor:
  image: binaryrepositorymanager-harbor
  version: 1.0.0
  harbor:
    url: https://<harbor-host>/api
    username: jenkins.harbor
    password: <undefined>
  resources:
    limits:
      cpu: "300m"
      memory: "500Mi"
    requests:
      cpu: "100m"
      memory: "200Mi"

kathra-catalog-icons:
  tls: true
  repository: 
    url: https://kathra-catalog-icons:_vi429_1RAAyezLv2wn9@git.kathra.org/KATHRA/kathra-catalog.git
    revision: 23a6c71e86f2d854669b959d657e1a7b9e8a2e60
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

kathra-catalog-updater:
  image: catalogupdater
  version: 1.0.0
  protocol: https
  repository:
    url: https://kathra-catalog-icons:_vi429_1RAAyezLv2wn9@git.kathra.org/KATHRA/kathra-catalog.git
    revision: 23a6c71e86f2d854669b959d657e1a7b9e8a2e60

kathra-catalogmanager:
  image: catalogmanager-helm
  version: 1.0.0
  tls: true
  services_url:
    resource_manager: http://resourcemanager.<base-domain-name>/api/v1
  resources:
    limits:
      cpu: 300m
      memory: 768Mi
    requests:
      cpu: 50m
      memory: 256Mi

kathra-codegen-swagger:
  image: codegen-swagger
  version: 1.0.0
  tls: true
  resources:
    limits:
      cpu: 300m
      memory: 768Mi
    requests:
      cpu: 50m
      memory: 256Mi


kathra-codegen-helm:
  image: codegen-helm
  version: 1.0.0
  tls: true
  resources:
    limits:
      cpu: 300m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

kathra-dashboard: 
  image: dashboard
  version: 1.0.0
  tls: true
  services_url:
    platform_manager: wss://platformmanager.<base-domain-name>/spm
    app_manager: https://appmanager.<base-domain-name>/api/v1
    resource_manager: http://resourcemanager.<base-domain-name>/api/v1
    base_domain: <base-domain-name>
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi

kathra-pipelinemanager:
  image: pipelinemanager-jenkins
  version: 1.0.0
  tls: true
  jenkins:
    url: https://<jenkins-host>
    username: kathra-pipelinemanager
    api_token: <undefined>
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

kathra-platformmanager:
  image: platformmanager-kube
  version: 1.0.0
  tls: true
  websocket:
    port: "8080"
  catalog_manager:
    url: http://catalogmanager/api/v1
  deployment:
    ingress_controller: traefik
    tld: <base-domain-name>
  resources:
    limits:
      cpu: 300m
      memory: 768Mi
    requests:
      cpu: 100m
      memory: 128Mi

kathra-resourcemanager:
  image: resourcemanager-arangodb
  version: 1.0.0
  tls: true
  arango:
    host: resource-db
    port: "8529"
    database: KATHRA
    user: root
    password: <undefined>
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 50m
      memory: 128Mi

db:
  password: <undefined>

kathra-sourcemanager:
  image: sourcemanager-gitlab
  version: 1.0.0
  tls: true
  temp_repos_folder: /tmp/kathra-sourcemanager-git-repos
  dir_creation_max_retry: "3"
  delete_temp_folder: "true"
  delete_temp_zip: "true"
  gitlab:
    url: https://<gitlab-host>
    api_token: <undefined>
    parent_group: kathra-projects
  user_manager:
    url: usermanager
  resources:
    limits:
      cpu: 300m
      memory: 768Mi
    requests:
      cpu: 50m
      memory: 128Mi


kathra-usermanager:
  image: usermanager-keycloak
  version: 1.0.0
  tls: true
  resources:
    limits:
      cpu: 300m
      memory: 768Mi
    requests:
      cpu: 50m
      memory: 128Mi
  keycloak:
    clientId: user-manager
    clientSecret: a375446d-7fec-421f-ae8e-65d523afa0b8

kathra-sync:
  keycloak:
    login: kathrausersynchronizer
    password: <undefined>
  image: users-sync
  version: 1.0.0
  resources:
    limits:
      cpu: 300m
      memory: 768Mi
    requests:
      cpu: 50m
      memory: 128Mi
