apiVersion: v1
data:
  KEYCLOAK_ADMIN_REALM: {{ .Values.keycloak.adminRealm | b64enc }}
  KEYCLOAK_ADMIN_CLIENT_ID: {{ .Values.keycloak.adminClientId | b64enc }}
  KEYCLOAK_ADMIN_USERNAME: {{ .Values.keycloak.adminUsername | b64enc }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.adminPassword | b64enc }}
kind: Secret
metadata:
  name: usermanager-secret
type: Opaque
