apiVersion: v1
data:
  KEYCLOAK_ADMIN_CLIENT_ID: {{ .Values.keycloak.clientId | b64enc }}
  KEYCLOAK_ADMIN_USERNAME: {{ .Values.keycloak.username | b64enc }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.password | b64enc }}
kind: Secret
metadata:
  name: usermanager-secret
type: Opaque
