apiVersion: v1
kind: Service
metadata:
  name: usermanager
  labels:
{{ include "kathra.labels" . | indent 4 }}
    app: usermanager
    project: kathra
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: usermanager
    project: kathra
  type: ClusterIP
