apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "kathra.labels" . | indent 4 }}
    app: usermanager
    impl: keycloak
    project: kathra
  name: usermanager-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermanager
      impl: keycloak
      project: kathra
  template:
    metadata:
      labels:
        app: usermanager
        impl: keycloak
        project: kathra
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KEYCLOAK_ADMIN_REALM
          valueFrom:
            secretKeyRef:
              key: KEYCLOAK_ADMIN_REALM
              name: usermanager-secret
        - name: KEYCLOAK_REALM
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_REALM
              name: keycloak-config
        - name: KEYCLOAK_ADMIN_AUTH_URL
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_ADMIN_AUTH_URL
              name: keycloak-config
        - name: KEYCLOAK_ADMIN_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_ADMIN_CLIENT_ID
              name: keycloak-config
        - name: KEYCLOAK_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              key: KEYCLOAK_ADMIN_USERNAME
              name: usermanager-secret
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: KEYCLOAK_ADMIN_PASSWORD
              name: usermanager-secret
        - name: KEYCLOAK_AUTH_URL
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_AUTH_URL
              name: keycloak-config
        - name: KEYCLOAK_REALM
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_REALM
              name: keycloak-config
        - name: KEYCLOAK_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: KEYCLOAK_CLIENT_ID
              name: keycloak-secret
        - name: KEYCLOAK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: KEYCLOAK_CLIENT_SECRET
              name: keycloak-secret
        - name: JAVA_OPTS
          value: "-XX:+UnlockExperimentalVMOptions  -XX:MaxRAMFraction=1 -Xms128M -Xmx512M"
        image: "{{ .Values.global.docker.registry.url }}/{{ .Values.global.docker.registry.root_repository }}/{{ .Values.image }}:{{ .Values.version }}"
        imagePullPolicy: Always
        name: usermanager-keycloak
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

