apiVersion:  apps/v1
kind: Deployment
metadata:
  name: kathra-codegen-swagger
  labels:
{{ include "kathra.labels" . | indent 4 }}
    app: codegen
    impl: swagger
    project: kathra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codegen
      impl: swagger
      project: kathra
  template:
    metadata:
      labels:
        app: codegen
        impl: swagger
        project: kathra
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: "{{ .Values.global.docker.registry.url }}/{{ .Values.global.docker.registry.root_repository }}/{{ .Values.image }}:{{ .Values.version }}"
        imagePullPolicy: Always
        name: codegen-swagger
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: ARTIFACT_REPOSITORY_URL
          valueFrom:
            configMapKeyRef:
              name: codegen-config
              key: ARTIFACT_REPOSITORY_URL
        - name: ARTIFACT_PIP_REPOSITORY_NAME
          valueFrom:
            configMapKeyRef:
              name: codegen-config
              key: ARTIFACT_PIP_REPOSITORY_NAME
        - name: JAVA_OPTS
          value: "-XX:+UnlockExperimentalVMOptions  -XX:MaxRAMFraction=1 -Xms128M -Xmx512M"
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}