apiVersion: v1
kind: Service
metadata:
  name: codegen-swagger
  labels:
{{ include "kathra.labels" . | indent 4 }}
    app: codegen
    product: kathra
    impl: swagger
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: codegen
    product: kathra
    impl: swagger
  type: ClusterIP