apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gitlab-create-backup
spec:
  schedule: "{{ .Values.backup.cron }}"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 10
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: gitlab-backup-robot 
          containers:
          - name: kubectl
            image: "{{ .Values.backup.kubectl.image }}:{{ .Values.backup.kubectl.tag }}"
            command:
            - /usr/local/bin/bash
            - -c
            - pod_name=$(kubectl -n {{ .Values.namespace }} get pods -l project=gitlab -o jsonpath='{.items[*].metadata.name}');
              kubectl -n {{ .Values.namespace }} get po/$pod_name;
              kubectl -n {{ .Values.namespace }} exec $pod_name -- gitlab-rake gitlab:backup:create
          restartPolicy: OnFailure
