---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-backup-robot

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-exec
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-exec-binding
subjects:
- kind: ServiceAccount
  name: gitlab-backup-robot 
roleRef:
  kind: Role
  name: pod-exec
  apiGroup: rbac.authorization.k8s.io
