apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    ingress: tls
spec:
  rules:
  - host: {{ .Values.fqdn }} 
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: 80
{{- with .Values.ingress.tls }}
  tls:
{{ toYaml . | indent 4 }}
{{- end }}
