{{ if .Values.global.docker.registry.secret }}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.global.docker.registry.secret }}
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
{{ end }}