---
apiVersion: v1
kind: Secret
metadata:
  name: kathra-keycloak-secret
  labels:
    project: kathra
    app: kathra-keycloak
type: Opaque
data:
  KEYCLOAK_CLIENT_ID: {{ .Values.global.keycloak.kathra_services_client.id | b64enc }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.global.keycloak.kathra_services_client.secret | b64enc }}