apiVersion: v1
data:
  KEYCLOAK_ADMIN_AUTH_URL: {{ .Values.global.keycloak.auth_url }}
  KEYCLOAK_ADMIN_CLIENT_ID: admin-cli
  KEYCLOAK_ADMIN_REALM: master
  KEYCLOAK_AUTH_URL: {{ .Values.global.keycloak.auth_url }}
  KEYCLOAK_REALM: {{ .Values.global.keycloak.realm }}
kind: ConfigMap
metadata:
  name: keycloak-config
  labels:
    project: kathra
    app: kathra-keycloak