apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
    {{- if eq .Values.configuration.persistence.resourcePolicy "keep" }}
    helm.sh/resource-policy: keep
    {{- end }}
  labels: 
    app: nfs-server
  name: nfs-pod-data
spec:
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.configuration.persistence.PVC_STORAGE_SIZE }}
