apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "binaryrepositorymanager-harbor"
  labels:
{{ include "kathra.labels" . | indent 4 }}
    product: kathra
    app: binaryrepositorymanager
    impl: "harbor"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        product: kathra
        app: binaryrepositorymanager
        impl: harbor
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: binaryrepositorymanager-harbor
        image: "{{ .Values.global.docker.registry.url }}/{{ .Values.global.docker.registry.root_repository }}/{{ .Values.image }}:{{ .Values.version }}"
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: HARBOR_URL
          valueFrom:
            configMapKeyRef:
              name: binaryrepositorymanager-config
              key: HARBOR_URL
        - name: HARBOR_USERNAME
          valueFrom:
            secretKeyRef:
              name: binaryrepositorymanager-secret
              key: HARBOR_USERNAME
        - name: HARBOR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: binaryrepositorymanager-secret
              key: HARBOR_PASSWORD
        - name: KEYCLOAK_AUTH_URL
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KEYCLOAK_AUTH_URL
        - name: KEYCLOAK_REALM
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KEYCLOAK_REALM
        - name: KEYCLOAK_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: kathra-keycloak-secret
              key: KEYCLOAK_CLIENT_ID
        - name: KEYCLOAK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: kathra-keycloak-secret
              key: KEYCLOAK_CLIENT_SECRET
        - name: JAVA_OPTS
          value: "-XX:+UnlockExperimentalVMOptions  -XX:MaxRAMFraction=1 -Xms128M -Xmx512M"
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}