apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: resource
    project: resource
  name: resource-arangodb-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: default