apiVersion: v1
kind: Secret
metadata:
  name: source-manager-secret
  labels:
{{ include "kathra.labels" . | indent 4 }}
    project: kathra
    app: source-manager
type: Opaque
data:
  KATHRA_SOURCEMANAGER_GITLAB_API_TOKEN: {{ .Values.gitlab.api_token | b64enc }}
  USERNAME: {{ .Values.keycloak.username | b64enc }}
  PASSWORD: {{ .Values.keycloak.password | b64enc }}