apiVersion: v1
kind: Secret
metadata:
  name: binaryrepositorymanager-nexus-secret
  labels:
{{ include "kathra.labels" . | indent 4 }}
    project: kathra
    app: binaryrepositorymanager
type: Opaque
data:
  NEXUS_USERNAME: {{ .Values.nexus.username | b64enc }}
  NEXUS_PASSWORD: {{ .Values.nexus.password | b64enc }}
  USERNAME: {{ .Values.keycloak.username | b64enc }}
  PASSWORD: {{ .Values.keycloak.password | b64enc }}