global:
  namespace: kathra-dev
  tld: dev-irtsysx.fr
  docker:
    registry: 
      url: registry.hub.docker.com
      root_repository: kathra
      secret_b64: <base64_k8s_dockerconfig_secret>
  keycloak:
    kathra_services_client:
      id: <kathra_services_client_id>
      secret: <kathra_services_client_secret>

image: catalogupdater
version: 1.0.1-SNAPSHOT
protocol: https
repository:
  url: https://catalog-puller:4nmg_PeHxcbUQjtCGvU3@git.kathra.org/KATHRA/kathra-catalog.git
  revision: f2d2c4950a733cac0a1a7c12852cefdf9ceba80c