---
apiVersion: v1
kind: ConfigMap
metadata:
  name: platformmanager-config
  labels:
{{ include "kathra.labels" . | indent 4 }}
    project: kathra
    app: platformmanager
data:
  WS_PORT: {{ .Values.websocket.port | quote }}
  KATHRA_CATALOGMANAGER_URL: {{ .Values.catalog_manager.url }}
  KATHRA_INGRESSCONTROLLER_NAME: {{ .Values.deployment.ingress_controller }}
  KATHRA_TOPLEVEL_DOMAIN: {{ .Values.deployment.tld }}