---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platformmanager
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kathra.labels" . | indent 4 }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: platformmanager-{{ .Release.Namespace }}-clusterrole
  labels:
{{ include "kathra.labels" . | indent 4 }}
rules:
- apiGroups: ['*']
  resources: ['*']
  verbs: ['create','delete','get','list','patch','update','watch']
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "platformmanager-{{ .Release.Namespace }}-clusterrolebinding"
  labels:
{{ include "kathra.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: platformmanager
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: platformmanager-{{ .Release.Namespace }}-clusterrole
  apiGroup: rbac.authorization.k8s.io