apiVersion: apps/v1
kind: Deployment
metadata:
  name: kathra-platformmanager-java
  labels:
{{ include "kathra.labels" . | indent 4 }}
    project: kathra
    app: platformmanager
    impl: java
spec:
  replicas: 1
  selector:
    matchLabels:
      project: kathra
      app: platformmanager
      impl: java
  template:
    metadata:
      labels:
        project: kathra
        app: platformmanager
        impl: java
    spec:
      serviceAccountName: platformmanager
      imagePullSecrets:
      - name: regcred
      containers:
      - image: "{{ .Values.global.docker.registry.url }}/{{ .Values.global.docker.registry.root_repository }}/{{ .Values.image }}:{{ .Values.version }}"
        imagePullPolicy: Always
        name: platformmanager-java
        env:
        - name: KATHRA_TOPLEVEL_DOMAIN
          value: {{ .Values.global.tld }}
        - name: KEYCLOAK_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: KEYCLOAK_CLIENT_ID
        - name: KEYCLOAK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: KEYCLOAK_CLIENT_SECRET
        - name: JAVA_OPTS
          value: "-XX:+UnlockExperimentalVMOptions  -XX:MaxRAMFraction=1 -Xms128M -Xmx512M"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}
